### ISSUE TITLE
Can't you "just" put this in the Google Store? :P

### ISSUE THREAD

**Issue by cauerego** [liuzheng/Personal-Blocklist-by-LZ#1]
I'm highly considering on doing it, if you won't. ;)

**Comment by cauerego** [comment]
Nevermind, I just noticed this is not done as it should:

https://www.reddit.com/r/chrome/comments/3esvzq/personal_blocklist_dead/ctqr1ev

**Comment by liuzheng** [comment]
@cauerego when finish it , I will
